### ISSUE TITLE
Teaserbild wird beim Resize nicht richtig geladen

### ISSUE THREAD

**Issue by cowboyxup** [pfadfinden/bdp_template#1]
Wenn die Seite in einem kleinen Browserfenster geladen wird und dann das Fenster vergrößert wird, dann werden alle Elemente bis auf das Teaserbild vergrößert, da hier das mobile Bild im speicher ist. Hier müsste mittels js das größere bild nachgeladen werden

**Comment by cowboyxup** [comment]
Der Resize funktioniert nicht nichtig, sowohl bei Firefox(getestet auf mehreren Rechnern) und auch beim iPad air (safari) sieht die anzeige so aus.
![img_0548](https://cloud.githubusercontent.com/assets/13420422/9520664/63d60794-4cc9-11e5-9a8d-5b6c19ceae6d.jpg)

**Comment by philippst** [comment]
@cowboyxup Das ist aber nicht die DEV-Version mit dem Polyfill, oder? Könntest du http://www.pfadfinden.de/?development[version]=12 mal testen?

**Comment by cowboyxup** [comment]
In der dev Version wird das Teaserbild bei großen Bildschirm auch groß geladen, im Moment wird es bei mir immer in der kleinen Version geladen. Der Resize von klein-->groß funktioniert aber auch in der dev-Version nicht.

**Comment by philippst** [comment]
Puh, zähes Thema. Habe jetzt sowohl in der Prod als auch Test Version nochmal ein paar Kleinigkeiten geändert. Kannst du es nochmal testen? Im IE klappt der Resize ganz gut :-) Danke und Grüße

**Comment by larsboehnke** [comment]
Resize im Safari und Chrome geht

**Comment by cowboyxup** [comment]
seit [firefox 45 gefixt](https://developer.mozilla.org/en-US/Firefox/Releases/45#HTML)
