### ISSUE TITLE
Kalender wird langgezogen dargestellt

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#12]
Der Kalender wird beim ersten Laden der Seite langgezogen dargestellt, später gequetscht.

**Comment by larsboehnke** [comment]
@philippst wollen wir den Kalender so lange mal deaktivieren? Finde das umprofessionell und nicht schön.

**Comment by philippst** [comment]
Bitte Browser-Cache leeren (Strg+F5) und retesten.
Habe Ablaufsteuerung in main.js angepasst.

**Comment by larsboehnke** [comment]
@philippst sieht gut aus!
