### ISSUE TITLE
Links der LVs sollten in externem Fenster öffnen

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#15]
Links der LVs sollten sich in einem externen Fenster öffnen: http://www.pfadfinden.de/kontakt/landesverbaende/

**Comment by philippst** [comment]
Individuelle Konfiguration, hat nichts direkt mit dem Template zu tun. Hab es mal auf _blank geändert. Vermutlich gibt es aber auch wieder ausreichend Personen, die kein Fan von dieser Konfiguration sind :-)
