### ISSUE TITLE
Wort-Bildmarke verschwindet beim navigieren

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#16]
Manchmal verschwindet nach dem navigieren zwischen den Seiten die Wort-BIldmarke
![bildschirmfoto 2015-09-02 um 20 22 49](https://cloud.githubusercontent.com/assets/11321756/9640192/9e40e64c-51b0-11e5-9a0a-cbcf545e40c6.png)

**Comment by larsboehnke** [comment]
![bildschirmfoto 2015-09-10 um 02 51 03](https://cloud.githubusercontent.com/assets/11321756/9777622/e3b7df9e-5766-11e5-90d7-b4385d03cab2.png)

**Comment by larsboehnke** [comment]
@philippst immer noch aktuell, ein schneller fix wäre hier wichtig! Tritt auch auf www.pfadfinderei.de auf

**Comment by philippst** [comment]
Ich kann diesen Fehler leider nicht strukturiert reproduzieren. Hat vielleicht jemand anders eine Idee? @corphi oder @cowboyxup ?

**Comment by corphi** [comment]
Safari… Dem habe ich auch ein Update für das Theme gewidmet. Ich kann diesen Fehler leider nicht reproduzieren (mit Epiphany, der auch auf webkit basiert). Bei den Hessen liegt aber noch mehr im Argen.

**Comment by larsboehnke** [comment]
Safari ist der neue IE.

**Comment by philippst** [comment]
Existiert der Fehler immer noch? Nur im Safari?

**Comment by larsboehnke** [comment]
Ja, im Safari. Chrome und Firefox geht alles.

**Comment by larsboehnke** [comment]
@philippst auf www.pfadfinderei.de noch existent
