### ISSUE TITLE
Klilie für Facebook og:image anbieten wenn kein gutes Bild auf der Seite ist

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#19]
Um gute Facebook Posts erstellen zu können, wäre es schön, wenn wir Facebook die Klilie als og:image anbieten können falls auf der Seite selbst kein gutes Bild zur Verfügung steht.

Aktuell wird z.B. beim posten einer Veranstaltung die Wort-Bild-Marke oder die Deutschlandkarte ausgelesen, was beides schlecht ist: http://www.pfadfinden.de/veranstaltung/calendar/2015/10/23/event/icalendar/medienworkshop/

Das Facebook URL Debugger Tool zeigt einem an, welche Daten Facebook ausliest: https://developers.facebook.com/tools/debug/

Auch die Meta-Beschreibung usw. ist bei einer Veranstaltung generisch für den BdP. Schöner wäre ein Text zur Veranstaltung.

**Comment by larsboehnke** [comment]
Aktuell sieht es so aus 
![bildschirmfoto 2015-09-30 um 11 40 58](https://cloud.githubusercontent.com/assets/11321756/10189717/544bb7ce-6768-11e5-9764-c892f6dfe7a2.png)

**Comment by philippst** [comment]
Welche Dateigröße/Format würdest du empfehlen? Aufgrund der viereckigen Verwendung vielleicht auch nicht rund sondern wie das Facebook Profilbild?

**Comment by larsboehnke** [comment]
@philippst ja das wäre toll. Oder mann schafft es, der Veranstaltung ein Bild zu geben, das klein angezeigt wird jedoch mind 1600x600 px ist (das ist die Größe ab der Facebook Thumbnails dann groß anzeigt).

Dateigröße und Format hatte ich bisher immer PNG, Dateigröße hängt von der oben beschriebenen Größe ab. Facebook empfiehlt eine hohe Auflösung für Hochauflösende Displays usw.: https://www.facebook.com/business/ads-guide/clicks-to-website/links/?toggle0=Foto

**Comment by cowboyxup** [comment]
Implementierung ist recht komplex, da z.B die News Erweiterung auch Open Graph Tags hinzufügt und dann Tags doppelt sind

**Comment by larsboehnke** [comment]
@cowboyxup hatte @philippst zwischenzeitlich schon gelöst!
