### ISSUE TITLE
Menüleiste vollständig ins responsive Theme integrieren

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#20]
Wichtige Punkte aus der Menüleiste wie die Ortsgruppensuche und die Links zu Einrichtungen und Social Media sind im responsiven Layout nicht verfügbar.

Eine mögliche Lösung könnte so aussehen wie im responsiven Layout von scoutingtrain.org umgesetzt.

**Comment by JoshuaWolff** [comment]
Eine gute Lösung wäre auch das ausklappen dieses Menüs durch einen zweiten klick.

Wie hier: http://start.bdpnrw.de

**Comment by larsboehnke** [comment]
@JoshuaWolff finde ich persönlich nicht so gut. Eher würde ich den Kaste dauerhaft über dem Footer verankern. 
![footer mit sub nav](https://cloud.githubusercontent.com/assets/11321756/10868713/3dcc3b0c-8097-11e5-8fd2-96293d5718c0.jpg)

**Comment by cowboyxup** [comment]
@JoshuaWolff Designtechnisch ist dein Vorschlag konseqent. Leider wird das zweimalige Klicken Verwirrung beim Nutzer auslösen. Der Nutzer erwartet das beim 2. Klick, das Menü sich wieder einklappt.

**Comment by cowboyxup** [comment]
2. Menüleiste wird im Mobilen Design über dem Footer angezeigt.
