### ISSUE TITLE
Besseres Layout für News Artikel

### ISSUE THREAD

**Issue by larsboehnke** [pfadfinden/bdp_template#24]
News Artikel sollten ein umfangreicheres Layout haben:
* größeres Bild, welches besser in den Text integriert ist
* Datum besser in das Layout integriert

**Comment by larsboehnke** [comment]
@cowboyxup wie sieht das Layout aus?

**Comment by cowboyxup** [comment]
![news_list_item](https://cloud.githubusercontent.com/assets/13420422/11451461/71a4267a-95c7-11e5-8dd9-22cc0be81cf3.PNG)
![news_single](https://cloud.githubusercontent.com/assets/13420422/11451462/71a5e53c-95c7-11e5-837a-ada48651192f.PNG)

**Comment by larsboehnke** [comment]
@cowboyxup beim Update könnte es ggf. zu Problemen kommen da die bisherigen Newsbilder alle nativ in der Teaser Auflösung hochgeladen wurden.

**Comment by cowboyxup** [comment]
@larsboehnke gerade getestet, kleinere Bilder werden einfach kleiner dargestellt, d. h. noch nach dem alten layout.
