### ISSUE TITLE
Schriftart Immenhausen

### ISSUE THREAD

**Issue by cowboyxup** [pfadfinden/bdp_template#25]
Schriftart akachen sollte durch Immenhausen ersetzt werden.

@philippst Fehler in http://cdn.pfadfinden.de/fonts/immenhausen/immenhausen.css gefunden! Dort sind alle pfade falsch. Die müssten statt cdn.pfadfinden.de/fonts/akachen/.... cdn.pfadfinden.de/fonts/immenhausen/.... heißen.

**Comment by philippst** [comment]
Tatsache. Den Fehler im CDN habe ich behoben. Schaffe es die Tage aber eher nicht, dass im CSS anzupassen. Machst du das?
