### ISSUE TITLE
Mehrspaltige Inhaltselemente

### ISSUE THREAD

**Issue by philippst** [pfadfinden/bdp_template#37]
Es ist gewünscht, Inhalte auch mehrspaltig im TYPO3 Template darzustellen. Darstellung z.B. 
wie auf http://www.pfadfinden.de/impressum/. Dies wird dort über die Extension Gridelements realisiert. 

Eine Quick&Dirty Lösung als Gist: https://gist.github.com/philippst/81eaaf1fa73883cff297

**Comment by cowboyxup** [comment]
@philippst funktioniert doch mit dem master schon
