### ISSUE TITLE
CSC-Default Wrapper um Inhaltselemente

### ISSUE THREAD

**Issue by philippst** [pfadfinden/bdp_template#51]
Seit Umstellung auf fluid_styled_content erhalten alle Content Elemente ein Wrapper Div mit class="csc-default". Das trifft auch bei Plugins zu. Problematisch ist, dass es Plugins wie z.B. tt_address gibt, auf deren Einstellung "Erscheinungsbild" -> "Layout" man keinen Einfluss nehmen kann. 

Sieht z.B. bei http://www.pfadfinden.de/kontakt/bundesamt/ nicht so gut aus.

**Comment by cowboyxup** [comment]
--- unterstützung nicht mehr für den 7.6.x Zweig ---
