### ISSUE TITLE
Seiten-TSconfig laut Wiki manuell übernehmen

### ISSUE THREAD

**Issue by philippst** [pfadfinden/bdp_template#52]
Hallo @cowboyxup,
laut Wiki (https://github.com/pfadfinden/bdp_template/wiki/Konfiguration) muss der Root PageTS manuell kopiert und auf der Root Seite eingefügt werden. Ist das kopieren noch erforderlich? Ich habe gesehen, dass das auch als verfügbares Objekt als SeitenTS-Config ausgewählt werden kann. Das wäre von der Benutzung natürlich einfacher.

**Comment by cowboyxup** [comment]
@philippst das kopieren ist kein muss, ich habe die Anleitung dem endsprechend angepasst. Ich finde es beim ersten Mal übersichtlicher, die eigenschaften komplett mit hirarchie zu übernehmen, da über den object-browser immer dann der gesammte pfad für die ts konstanten einfach in der Reihenfolge des änderns eingefügt wird.
