### ISSUE TITLE
Statische Templates einbinden

### ISSUE THREAD

**Issue by philippst** [pfadfinden/bdp_template#53]
Hallo @cowboyxup,
in der Wiki unter https://github.com/pfadfinden/bdp_template/wiki/Konfiguration bin ich darauf gestoßen, dass css_styled_content noch eingebunden werden soll. Ich vermute mal korrekt ist fluid_styled_content. Ist zusätzlich auch fluid_styled_content_css erforderlich? Letztes ist laut TYPO3 ja optional.

**Comment by cowboyxup** [comment]
anleitung korrigiert und fluid_styled_content_css muss mit eingebunden werden
