### ISSUE TITLE
Links und Absätze in Kalender Event View

### ISSUE THREAD

**Issue by philippst** [pfadfinden/bdp_template#63]
Die Kalender Einzelansicht (Event View) rendert zwar Text fett, unterstützt aber keine Absätze und auch keine Verlinkungen. Die Erfassung von Absätzen und Links ist im RTE möglich, wird aber wohl nicht ausgegeben.

Beispiel: http://www.pfadfinden.de/veranstaltung/calendar/2016/11/11/event/?tx_cal_controller%5Buid%5D=63&cHash=adb135742427df454d4969a6953f2181

Vielleicht hat Christian eine Idee?

**Comment by cowboyxup** [comment]
Das liegt an der cal Unterstützung für fluid_styled content. Damit die Beschreibung überhabt angezeigt wird gibt es diesen Trick:
# dirty fix for rendering description in fluid_styles_content
tt_content.text {
    20 = TEXT
    20 {
        field = bodytext
        required = 1
        description.parseFunc = < lib.parseFunc_RTE
    }
}
Hier müsste ein Weg gefunden werden den Text durch die html-parser funktion zu schicken, sodass die html-tags nicht entfernt werden
